const translate = document.querySelectorAll("[data-translate]");

const languages = {
    "en": {
        "li1": "About HIRPO",
        "li2": "Pricing & Bills",
        "li3": "Contact Us",
        "li4": "Request Demo",
        "li5": "Privacy Policy",
        "heading1": "Ready and easy to use performance management solutions ",
        "login": "Login",
        "get_started": "Get Started",
        "text1": "Hirpo enables you to easily automate 70% of the solution process through the information available in the database. With Hirpo, you can effectively carry out the performance evaluation process of your employees. ",
        "text2": "Save time on performance evaluations that would typically take months. We can handle it for you in just ",
        "text3": "3 hours",
        "text4": "Hirpo's proposed impact allows you to save time through automated solutions. We can efficiently handle these time-consuming stages that would typically take months using our accumulated data, completing them in a very short time. ",
        "icon1": "Time Saving",
        "icon2": "User Friendly",
        "icon3": "Secure",
        "heading2": "Ready to see how it works?",
        "text5": " First, go through the registration process for Hirpo",
        "text6": "Proceed to the Wizard",
        "text7": "Simply answer 3 questions",
        "text18": "Start the magic in a short time",
        "heading3": "Do you have a question?",
        "label1": "Name",
        "label2": "Email",
        "send": "Send",
        "heading4": "Choose a plan tailored to your needs",
        "month": "Monthly",
        "year": "Yearly",
        "sale": "25% OFF",
        "plan1": "Small Enterprise Plan",
        "plan2": "Medium Enterprise Plan",
        "plan3": "Large Enterprise Plan",
        "plan4": "Corporate Enterprise Plan",
        "per_month": "per month",
        "employees": "Employees",
        "trial": "1 Month Free Trial",
        "wizard": "Wizard",
        "self_editing": "Self Editing",
        "6_months": "6 Month Plan",
        "1_year": "1 Year Plan",
        "get_plan": "Get Plan",
        "3_m": "3 Month",
        "6_m": "6 Month",
        "1_y": "Yearly",
        "per_3_m": "for 3 months",
        "per_6_m": "for 6 months",
        "per_1_y": "for yearly",
        "customers": "Customers",
        "contact_heading": "We are here to help you grow",
        "contact_subheading": "Tell us what you need and our team will reach out shortly.",
        "contact_form_title": "Send us a message",
        "contact_form_desc": "Fill out the form and we will get back to you within one business day.",
        "contact_info_title": "Contact details",
        "contact_info_phone": "Phone: +994 70 294 50 70",
        "contact_info_email": "Email: info@hirpo.net",
        "contact_info_address": "Address: Baku, Azerbaijan",
        "contact_info_response": "We respond Monday to Friday, 09:00-18:00 (GMT+4).",
        "about_heading": "AI-powered HR technology for smarter people operations",
        "about_subheading": "Hirpo combines intuitive design with Agentic AI to automate workflows, surface insights, and help teams grow with confidence.",
        "about_story_title": "Why Hirpo",
        "about_story_body1": "Hirpo is an AI-powered HR technology platform built to help companies manage people smarter — across recruitment, performance, learning, and analytics.",
        "about_story_body2": "We believe HR should be simple, data-driven, and human-centered. That is why we blend intuitive design with Agentic AI capabilities so HR teams can automate operations, gain real-time insights, and make informed decisions that drive growth.",
        "about_mission_title": "Built for growing teams",
        "about_mission_body": "Designed for SMEs and scaling organizations, Hirpo delivers affordable tools that modernize HR operations without complexity.",
        "about_values_title": "Core modules",
        "about_module_1": "Employee Journey Dashboard – real-time visibility into people metrics and movements.",
        "about_module_2": "Performance & Satisfaction – track goals, competencies, and engagement.",
        "about_module_3": "Recruitment (ATS) – automate hiring and find the right candidates faster.",
        "about_module_4": "Learning (LMS) – manage onboarding, courses, and development plans.",
        "about_module_5": "HR Analytics – actionable insights and predictive dashboards for leadership.",
        "about_highlight_title": "Human-centered, data-driven HR",
        "about_highlight_body": "By merging technology and empathy, Hirpo nurtures a culture of performance, transparency, and continuous growth.",
        "about_location_label": "📍",
        "about_location_text": "Built in Azerbaijan, powered by global vision.",
        "about_site_label": "🌐",
        "about_site_text": "Learn more: hirpo.net",
        "about_cta_title": "Ready to transform your people operations?",
        "about_cta_button": "Request a demo",
        "privacy_heading": "Privacy Policy",
        "privacy_updated": "Last updated: October 1, 2025",
        "privacy_intro": "At Hirpo, your privacy is our priority. We respect the confidentiality of every user of our platform and services, and we clearly explain how your data is collected, used, and protected.",
        "privacy_section": "At Hirpo, your privacy is our priority. We respect the confidentiality of every user of our platform and services, and we clearly explain how your data is collected, used, and protected. We may collect personal information such as your name, email, phone number, and company details, as well as technical information like IP address, browser type, and device data.This information is used solely to improve service quality, ensure security, and provide technical support. Your data is shared only with trusted technical partners or when required by law.Hirpo never sells or trades your personal information.You may contact us anytime to request deletion or correction of your data. "
    },
    "az": {
        "li1": "HIRPO haqqında",
        "li2": "Qiymətlər",
        "li3": "Bizimlə Əlaqə",
        "li4": "Demo Tələb Et",
        "li5": "Məxfilik Siyasəti",
        "heading1": "Hər an istifadəyə hazır performans idarəetmə həlləri",
        "login": "Giriş",
        "get_started": "Başla",
        "text1": "Hirpo vasitəsilə verilənlər bazasında mövcud olan məlumatlar əsasında həll prosesinin 70%-ni asanlıqla avtomatlaşdıra bilərsiniz. Hirpo ilə işçilərinizin performans qiymətləndirmə prosesini effektiv şəkildə həyata keçirə bilərsiniz.",
        "text2": "Adi halda aylar çəkən performans qiymətləndirmələrindən vaxt qazanın. Biz bunu sizin üçün yalnız",
        "text3": "3 saatda",
        "text4": "Hirpo təklif olunan təsir vasitəsilə avtomatlaşdırılmış həllər vasitəsilə vaxt qazanmağa imkan verir. Biz bu vaxt itkiləri ilə əlaqədar mərhələləri bizim toplanmış məlumatlarımızı istifadə edərək effektiv şəkildə idarə edə bilərik və onlarla çox qısa bir zamanda başa çıxa bilərik. ",
        "icon1": "Vaxt Qazandırır",
        "icon2": "İstifadəsi Asandır",
        "icon3": "Təhlükəsizdir",
        "heading2": "Necə işlədiyini görmək üçün hazırsınız?",
        "text5": " Əvvəlcə Hirpo üçün qeydiyyat prosesindən keçin",
        "text6": "Möcüzəyə keçin",
        "text7": "Sadəcə 3 sual cavablayın",
        "text18": "Qısa zamanda sehrə başlayın",
        "heading3": "Sualınız var?",
        "label1": "Ad",
        "label2": "Email",
        "send": "Göndər",
        "heading4": "Öz ehtiyaclarınıza uyğun planı seçin",
        "month": "Aylıq",
        "year": "İllik",
        "sale": "25% ENDİRİM",
        "plan1": "Kiçik Biznes Planı",
        "plan2": "Orta Biznes Planı",
        "plan3": "Böyük Biznes Planı",
        "plan4": "Korporativ Biznes Planı",
        "per_month": "aylıq",
        "employees": "İşçi",
        "trial": "1 Ay Pulsuz Sınaq",
        "wizard": "Möcüzə",
        "self_editing": "Özün Redaktə Et",
        "6_months": "6 Aylıq Plan",
        "1_year": "1 İllik Plan",
        "get_plan": "Planı Al",
        "3_m": "3 Ay",
        "6_m": "6 Ay",
        "1_y": "İllik",
        "per_3_m": "3 ay üçün",
        "per_6_m": "6 ay üçün",
        "per_1_y": "illik üçün",
        "customers": "Müştərilər",
        "contact_heading": "Biz sizin inkişafınıza dəstək oluruq",
        "contact_subheading": "Tələbinizi bizimlə bölüşün, komandamız qısa zamanda sizinlə əlaqə saxlayacaq.",
        "contact_form_title": "Bizə mesaj göndərin",
        "contact_form_desc": "Formu doldurun və biz bir iş günü ərzində cavab verəcəyik.",
        "contact_info_title": "Əlaqə məlumatları",
        "contact_info_phone": "Telefon: +994 70 294 50 70",
        "contact_info_email": "E-poçt: info@hirpo.net",
        "contact_info_address": "Ünvan: Bakı, Azərbaycan",
        "contact_info_response": "Mesajlara bazar ertəsi - cümə, 09:00-18:00 (GMT+4) aralığında cavab veririk.",
        "about_heading": "Daha ağıllı insan resursları əməliyyatları üçün süni intellektlə gücləndirilmiş HR texnologiyası",
        "about_subheading": "Hirpo, Agentik AI imkanları ilə intuitiv dizaynı birləşdirərək iş axınlarını avtomatlaşdırır, insight-lar təqdim edir və komandaların inamla böyüməsinə kömək edir.",
        "about_story_title": "Niyə Hirpo",
        "about_story_body1": "Hirpo, işə qəbuldan performansa, öyrənmədən analitikaya qədər şirkətlərin insan resurslarını daha ağıllı idarə etməsinə kömək edən süni intellektlə gücləndirilmiş HR platformasıdır.",
        "about_story_body2": "Biz inanırıq ki, HR sadə, məlumat yönümlü və insan mərkəzli olmalıdır. Bu səbəbdən intuitiv dizaynı Agentik AI imkanları ilə birləşdiririk ki, HR komandaları əməliyyatları avtomatlaşdırsın, real vaxt analitikaları əldə etsin və inkişafı sürətləndirən qərarlar versin.",
        "about_mission_title": "Böyüyən komandalar üçün",
        "about_mission_body": "KOB-lar və genişlənən təşkilatlar üçün hazırlanan Hirpo, HR əməliyyatlarını mürəkkəblik olmadan modernləşdirən əlçatan alətlər təqdim edir.",
        "about_values_title": "Əsas modullar",
        "about_module_1": "Employee Journey Dashboard – insan kapitalı göstəricilərinə və hərəkətlərinə real vaxt baxış.",
        "about_module_2": "Performance & Satisfaction – hədəfləri, kompetensiyaları və əməkdaş məmnuniyyətini izləyin.",
        "about_module_3": "Recruitment (ATS) – işə götürmə prosesini avtomatlaşdırın və düzgün namizədləri daha tez tapın.",
        "about_module_4": "Learning (LMS) – adaptasiya, kurslar və inkişaf planlarını idarə edin.",
        "about_module_5": "HR Analitikası – rəhbərlik üçün praktik insight-lar və proqnozlaşdırıcı panelər.",
        "about_highlight_title": "İnsan mərkəzli, məlumat yönümlü HR",
        "about_highlight_body": "Texnologiyanı və empatiyanı birləşdirərək, Hirpo performans, şəffaflıq və davamlı inkişaf mədəniyyətini gücləndirir.",
        "about_location_label": "📍",
        "about_location_text": "Azərbaycanla tikilib, qlobal vizyonla güclənir.",
        "about_site_label": "🌐",
        "about_site_text": "Daha ətraflı: hirpo.net",
        "about_cta_title": "İnsan resursları əməliyyatlarınızı çevirməyə hazırsınız?",
        "about_cta_button": "Demo tələb et",
        "privacy_heading": "Məxfilik Siyasəti",
        "privacy_updated": "Son yeniləmə: 1 oktyabr 2025",
        "privacy_intro": "Hirpo-da məxfiliyiniz bizim prioritetimizdir. Platformamızın və xidmətlərimizin hər bir istifadəçisinin məxfiliyinə hörmət edirik və məlumatlarınızın necə toplanıldığını, istifadə edildiyini və qorunduğunu açıq şəkildə izah edirik.",
        "privacy_section": "Hirpo olaraq, sizin şəxsi məlumatlarınızın qorunması bizim üçün prioritetdir. Biz platformamızı və xidmətlərimizi istifadə edən hər kəsin məlumat təhlükəsizliyinə hörmətlə yanaşırıq və bu məlumatların necə toplandığını, istifadə olunduğunu və qorunduğunu açıq şəkildə paylaşmaq istəyirik. Toplana biləcək məlumatlara ad, soyad, e- poçt, əlaqə nömrəsi və şirkət məlumatı daxildir.Saytdan istifadə zamanı IP ünvanı, brauzer növü və cihaz tipi kimi texniki məlumatlar da qeydə alına bilər.Bu məlumatlardan yalnız xidmət keyfiyyətini artırmaq, təhlükəsizlik və texniki dəstək məqsədilə istifadə olunur. Məlumatlar yalnız texniki tərəfdaşlarla və qanuni tələblər halında paylaşılır.Hirpo heç bir halda istifadəçi məlumatlarını kommersiya məqsədilə satmır.İstənilən vaxt bizə müraciət edərək məlumatlarınızın silinməsini və ya düzəldilməsini tələb edə bilərsiniz."
    },
    "ru": {
        "li1": "О HIRPO",
        "li2": "Цены",
        "li3": "Свяжитесь с нами",
        "li4": "Запросить демо",
        "li5": "Политика конфиденциальности",
        "heading1": "Готовые к использованию решения по управлению производительностью",
        "login": "Вход",
        "get_started": "Начать",
        "text1": "Hirpo позволяет вам легко автоматизировать 70% процесса решения на основе информации, доступной в базе данных. С Hirpo вы можете эффективно проводить процесс оценки производительности ваших сотрудников.",
        "text2": "Экономьте время на производительности, которая обычно занимает месяцы. Мы можем справиться с этим за вас всего за",
        "text3": "3 часа",
        "text4": "Предлагаемый Hirpo влияние позволяет вам экономить время благодаря автоматизированным решениям. Мы можем эффективно справиться с этими трудоемкими этапами, которые обычно занимают месяцы, используя наши накопленные данные, завершая их за очень короткое время. ",
        "icon1": "Экономит Время",
        "icon2": "Удобен в использовании",
        "icon3": "Безопасен",
        "heading2": "Готовы увидеть, как это работает?",
        "text5": " Сначала пройдите процесс регистрации для Hirpo",
        "text6": "Перейти к Волшебнику",
        "text7": "Просто ответьте на 3 вопроса",
        "text18": "Запустите магию в короткие сроки",
        "heading3": "У вас есть вопрос?",
        "label1": "Имя",
        "label2": "Емайл",
        "send": "Отправить",
        "heading4": "Выберите план, подходящий для ваших потребностей",
        "month": "Ежемесячно",
        "year": "Ежегодно",
        "sale": "25% СКИДКА",
        "plan1": "План малого предприятия",
        "plan2": "План среднего предприятия",
        "plan3": "План крупного предприятия",
        "plan4": "План корпоративного предприятия",
        "per_month": "в месяц",
        "employees": "Работник",
        "trial": "1 месяц бесплатно",
        "wizard": "Волшебник",
        "self_editing": "Самостоятельное редактирование",
        "6_months": "6 месяцев",
        "1_year": "1 год",
        "get_plan": "Получить план",
        "3_m": "3 месяца",
        "6_m": "6 месяцев",
        "1_y": "Год",
        "per_3_m": "за 3 месяца",
        "per_6_m": "за 6 месяцев",
        "per_1_y": "за год",
        "customers": "Клиенты",
        "contact_heading": "Мы помогаем вашему росту",
        "contact_subheading": "Расскажите нам о своей потребности, и наша команда свяжется с вами в ближайшее время.",
        "contact_form_title": "Отправьте нам сообщение",
        "contact_form_desc": "Заполните форму, и мы ответим в течение одного рабочего дня.",
        "contact_info_title": "Контактные данные",
        "contact_info_phone": "Телефон: +994 70 294 50 70",
        "contact_info_email": "Электронная почта: info@hirpo.net",
        "contact_info_address": "Адрес: Баку, Азербайджан",
        "contact_info_response": "Мы отвечаем с понедельника по пятницу, 09:00-18:00 (GMT+4).",
        "about_heading": "HR-технологии на базе ИИ для более умного управления людьми",
        "about_subheading": "Hirpo объединяет интуитивный дизайн с Agentic AI, чтобы автоматизировать процессы, раскрывать инсайты и помогать командам уверенно расти.",
        "about_story_title": "Почему Hirpo",
        "about_story_body1": "Hirpo — HR-платформа на базе ИИ, созданная, чтобы помогать компаниям управлять людьми более эффективно — от рекрутинга и производительности до обучения и аналитики.",
        "about_story_body2": "Мы считаем, что HR должен быть простым, основанным на данных и ориентированным на человека. Поэтому мы соединяем интуитивный дизайн с возможностями Agentic AI, чтобы HR-команды могли автоматизировать операции, получать инсайты в реальном времени и принимать взвешенные решения для роста.",
        "about_mission_title": "Для растущих команд",
        "about_mission_body": "Созданный для малого и среднего бизнеса и растущих компаний, Hirpo предлагает доступные инструменты, которые модернизируют HR-процессы без лишней сложности.",
        "about_values_title": "Ключевые модули",
        "about_module_1": "Панель Employee Journey — видимость показателей и перемещений сотрудников в реальном времени.",
        "about_module_2": "Performance & Satisfaction — отслеживайте цели, компетенции и вовлечённость.",
        "about_module_3": "Recruitment (ATS) — автоматизируйте найм и быстрее находите подходящих кандидатов.",
        "about_module_4": "Learning (LMS) — управляйте адаптацией, курсами и планами развития.",
        "about_module_5": "HR Analytics — практичные инсайты и предиктивные дашборды для руководства.",
        "about_highlight_title": "HR, ориентированный на человека и данные",
        "about_highlight_body": "Объединяя технологии и эмпатию, Hirpo формирует культуру производительности, прозрачности и постоянного развития.",
        "about_location_label": "📍",
        "about_location_text": "Создано в Азербайджане, усилено глобальным видением.",
        "about_site_label": "🌐",
        "about_site_text": "Узнайте больше: hirpo.net",
        "about_cta_title": "Готовы трансформировать работу с персоналом?",
        "about_cta_button": "Запросить демо",
        "privacy_heading": "Политика конфиденциальности",
        "privacy_updated": "Последнее обновление: 1 октября 2025 г.",
        "privacy_intro": "В Hirpo ваша конфиденциальность — наш приоритет. Мы уважительно относимся к каждому пользователю нашей платформы и услуг и прозрачно объясняем, как собираем, используем и защищаем ваши данные.",
        "privacy_section": "В Hirpo ваша конфиденциальность — наш приоритет. Мы уважаем конфиденциальность каждого пользователя нашей платформы и сервисов и чётко объясняем, как ваши данные собираются, используются и защищаются. Мы можем собирать персональные данные, такие как ваше имя, адрес электронной почты, номер телефона и данные компании, а также техническую информацию, такую ​​как IP- адрес, тип браузера и данные устройства.Эта информация используется исключительно для улучшения качества обслуживания, обеспечения безопасности и предоставления технической поддержки. Ваши данные передаются только доверенным техническим партнёрам или в случаях, предусмотренных законом.Hirpo никогда не продаёт и не обменивает ваши персональные данные.Вы можете связаться с нами в любое время, чтобы запросить удаление или исправление ваших данных.",
    }
}

let currentLanguage = "en";

function translatePage(e) {
    translate.forEach(element => {
        const key = element.dataset.translate;
        element.textContent = languages[e.value][key];
    });
}

translatePage({ value: currentLanguage });
