const translate = document.querySelectorAll("[data-translate]");

const languages = {
    "en": {
        "li1":"About HIRPO",
        "li2":"Pricing & Bills",
        "li3":"Contact Us",
        "heading1": "Ready and easy to use performance management solutions ",
        "login":"Login",
        "get_started":"Get Started",
        "text1":"Hirpo enables you to easily automate 70% of the solution process through the information available in the database. With Hirpo, you can effectively carry out the performance evaluation process of your employees. ",
        "text2":"Save time on performance evaluations that would typically take months. We can handle it for you in just ",
        "text3":"3 hours",
        "text4": "Hirpo's proposed impact allows you to save time through automated solutions. We can efficiently handle these time-consuming stages that would typically take months using our accumulated data, completing them in a very short time. ",
        "icon1":"Time Saving",
        "icon2":"User Friendly",
        "icon3":"Secure",
        "heading2": "Ready to see how it works?",
        "text5": " First, go through the registration process for Hirpo",
        "text6": "Proceed to the Wizard",
        "text7": "Simply answer 3 questions",
        "text18": "Start the magic in a short time",
        "heading3": "Do you have a question?",
        "label1": "Name",
        "label2": "Email",
        "send": "Send",
        "heading4": "Choose a plan tailored to your needs",
        "month": "Monthly",
        "year": "Yearly",
        "sale": "25% OFF",
        "plan1": "Small Enterprise Plan",
        "plan2": "Medium Enterprise Plan",
        "plan3": "Large Enterprise Plan",
        "plan4": "Corporate Enterprise Plan",
        "per_month": "per month",
        "employees": "Employees",
        "trial": "1 Month Free Trial",
        "wizard": "Wizard",
        "self_editing": "Self Editing",
        "6_months": "6 Month Plan",
        "1_year": "1 Year Plan",
        "get_plan": "Get Plan",
        "3_m": "3 Month",
        "6_m": "6 Month",
        "1_y": "Yearly",
        "per_3_m": "for 3 months",
        "per_6_m": "for 6 months",
        "per_1_y": "for yearly",
        "customers": "Customers",
    },
    "az": {
        "li1":"HIRPO haqqında",
        "li2":"Qiymətlər",
        "li3":"Bizimlə Əlaqə",
        "heading1": "Hər an istifadəyə hazır performans idarəetmə həlləri",
        "login":"Giriş",
        "get_started":"Başla",
        "text1":"Hirpo vasitəsilə verilənlər bazasında mövcud olan məlumatlar əsasında həll prosesinin 70%-ni asanlıqla avtomatlaşdıra bilərsiniz. Hirpo ilə işçilərinizin performans qiymətləndirmə prosesini effektiv şəkildə həyata keçirə bilərsiniz.",
        "text2":"Adi halda aylar çəkən performans qiymətləndirmələrindən vaxt qazanın. Biz bunu sizin üçün yalnız",
        "text3":"3 saatda",
        "text4": "Hirpo təklif olunan təsir vasitəsilə avtomatlaşdırılmış həllər vasitəsilə vaxt qazanmağa imkan verir. Biz bu vaxt itkiləri ilə əlaqədar mərhələləri bizim toplanmış məlumatlarımızı istifadə edərək effektiv şəkildə idarə edə bilərik və onlarla çox qısa bir zamanda başa çıxa bilərik. ",
        "icon1":"Vaxt Qazandırır",
        "icon2":"İstifadəsi Asandır",
        "icon3":"Təhlükəsizdir",
        "heading2": "Necə işlədiyini görmək üçün hazırsınız?",
        "text5": " Əvvəlcə Hirpo üçün qeydiyyat prosesindən keçin",
        "text6": "Möcüzəyə keçin",
        "text7": "Sadəcə 3 sual cavablayın",
        "text18": "Qısa zamanda sehrə başlayın",
        "heading3": "Sualınız var?",
        "label1": "Ad",
        "label2": "Email",
        "send": "Göndər",
        "heading4": "Öz ehtiyaclarınıza uyğun planı seçin",
        "month": "Aylıq",
        "year": "İllik",
        "sale": "25% ENDİRİM",
        "plan1": "Kiçik Biznes Planı",
        "plan2": "Orta Biznes Planı",
        "plan3": "Böyük Biznes Planı",
        "plan4": "Korporativ Biznes Planı",
        "per_month": "aylıq",
        "employees": "İşçi",
        "trial": "1 Ay Pulsuz Sınaq",
        "wizard": "Möcüzə",
        "self_editing": "Özün Redaktə Et",
        "6_months": "6 Aylıq Plan",
        "1_year": "1 İllik Plan",
        "get_plan": "Planı Al",
        "3_m": "3 Ay",
        "6_m": "6 Ay",
        "1_y": "İllik",
        "per_3_m": "3 ay üçün",
        "per_6_m": "6 ay üçün",
        "per_1_y": "illik üçün",
        "customers": "Müştərilər",
    },
    "ru": {
        "li1":"О HIRPO",
        "li2":"Цены",
        "li3":"Свяжитесь с нами",
        "heading1": "Готовые к использованию решения по управлению производительностью",
        "login":"Вход",
        "get_started":"Начать",
        "text1":"Hirpo позволяет вам легко автоматизировать 70% процесса решения на основе информации, доступной в базе данных. С Hirpo вы можете эффективно проводить процесс оценки производительности ваших сотрудников.",
        "text2":"Экономьте время на производительности, которая обычно занимает месяцы. Мы можем справиться с этим за вас всего за",
        "text3":"3 часа",
        "text4": "Предлагаемый Hirpo влияние позволяет вам экономить время благодаря автоматизированным решениям. Мы можем эффективно справиться с этими трудоемкими этапами, которые обычно занимают месяцы, используя наши накопленные данные, завершая их за очень короткое время. ",
        "icon1":"Экономит Время",
        "icon2":"Удобен в использовании",
        "icon3":"Безопасен",
        "heading2": "Готовы увидеть, как это работает?",
        "text5": " Сначала пройдите процесс регистрации для Hirpo",
        "text6": "Перейти к Волшебнику",
        "text7": "Просто ответьте на 3 вопроса",
        "text18": "Запустите магию в короткие сроки",
        "heading3": "У вас есть вопрос?",
        "label1": "Имя",
        "label2": "Емайл",
        "send": "Отправить",
        "heading4": "Выберите план, подходящий для ваших потребностей",
        "month": "Ежемесячно",
        "year": "Ежегодно",
        "sale": "25% СКИДКА",
        "plan1": "План малого предприятия",
        "plan2": "План среднего предприятия",
        "plan3": "План крупного предприятия",
        "plan4": "План корпоративного предприятия",
        "per_month": "в месяц",
        "employees": "Работник",
        "trial": "1 месяц бесплатно",
        "wizard": "Волшебник",
        "self_editing": "Самостоятельное редактирование",
        "6_months": "6 месяцев",
        "1_year": "1 год",
        "get_plan": "Получить план",
        "3_m": "3 месяца",
        "6_m": "6 месяцев",
        "1_y": "Год",
        "per_3_m": "за 3 месяца",
        "per_6_m": "за 6 месяцев",
        "per_1_y": "за год",
        "customers": "Клиенты",
    }
}

let currentLanguage = "en";

function translatePage(e) {
    translate.forEach(element => {
        const key = element.dataset.translate;
        element.textContent = languages[e.value][key];
    });
}

translatePage({value: currentLanguage});
